const correcoes = {
    "Descricao":"Descrição",
    "VlMin":"Valor Mínimo",
    "VlMax":"Valor Máximo",
    "Funcao":"Função",
    "Abreviacao":"Abreviação",
    "Nivel":"Nível",
    "Formula":"Fórmula",
    "id":"Id",
    "descricao":"Descrição",
    "vl Min":"Valor Mínimo",
    "vl Max":"Valor Máximo",
    "status":"Status",
    "formula Enum":"Fórmula",
    "grandeza":"Grandeza",
    "unidade":"Unidade",
    "funcao":"Função",
    "formula Enum":"Fórmula",
    "valor":"Valor",
    "UM":"Um",
    "DOIS":"Dois",
    "TRES":"Três",
    "QUATRO":"Quatro",
    "vlMin":"Valor Mínimo",
    "vlMax":"Valor Máximo",
    "formula":"Fórmula",
    "enderecoCLP":"Endereco CLP",
    "tipoUso":"Tipo de Uso",
    "pontoControle":"Ponto Controle",
    "clpTipo":"CLP Tipo",
    "DESCRICAO":"Descrição",
    "DATAHORA":"Data Hora",
    "STATUS":"Status",
    "USER":"Usuário",
    "ID":"Id",
    "PARAMETRO":"Parâmetro",
    "PARAMETROANTERIOR":"Parâmetro Anterior",
    "abreviacao":"Abreviação",
    "tamanho":"Tamanho",
    "offset":"Offset",
    "nivel":"Nível",
    "login":"Login",
    "unidades":"Unidades",
    "parametros":"Parâmetros",
}

export default correcoes;